<ModoCalentamiento>:
    orientation: 'vertical'
    padding: 20
    spacing: 20
    Label:
        text: "MODO 1: CALENTAMIENTO"
        bold: True
    BoxLayout:
        size_hint_y: None
        height: '40dp'
        text: "Tiempo (s):"
        TextInput:
            id: t_cal
            text: "10"
            input_filter: 'int'
            multiline: False
    Button:
        text: "INICIAR CALENTAMIENTO"
        on_release: root.ejecutar(t_cal.text)
    Widget: