<ModoOpenLoop>:
    orientation: 'vertical'
    padding: 20
    spacing: 20
    Label:
        text: "MODO 2: OPEN LOOP RESPONSE"
        bold: True
    BoxLayout:
        size_hint_y: None
        height: '40dp'
        text: "Tiempo (s):"
        TextInput:
            id: t_open
            text: "20"
            input_filter: 'int'
            multiline: False
    Button:
        text: "INICIAR OPEN LOOP"
        on_release: root.ejecutar(t_open.text)
    Widget: